version: "3.8"

services:
  frontend:
    build: ./Landing_Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Landing_Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://diazalvar.site/api
    depends_on:
      - backend

  backend:
    build: ./Landing-Backend
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=landing_contact
      - PORT=3000
      - JWT_SECRET=clave_secreta_873465
      - RECAPTCHA_SECRET_KEY=6LcUZmsrAAAAAKqbQe2LTtcTSsP88zjMxz5qBiOH
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: landing_contact
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
